language: android

jdk:
  - oraclejdk8

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

#android:
#  components:
#    - tools
#    - platform-tools
#    - android-26
#    - build-tools-26.0.2
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.2
  - echo y | android update sdk -u -a -t android-26
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_script:
   # Create and start an emulator for instrumentation tests.
    - chmod +x gradlew
    - chmod +x ./travis_build.sh
# script for build and release via Travis to Bintray
script: ./travis_build.sh

notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
